"""create metalprice table

Revision ID: 11b6aa1ea89a
Revises: adcf3bc00f9a
Create Date: 2026-10-01 14:14:55.532342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '11b6aa1ea89a'
down_revision: Union[str, Sequence[str], None] = 'adcf3bc00f9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The "metal" enum type already exists (created with the purchase table).
# On PostgreSQL, reuse it rather than trying to create it a second time.
metal_enum = sa.Enum(
    "GOLD", "SILVER", "PLATINUM", "PALLADIUM", name="metal"
).with_variant(
    postgresql.ENUM(
        "GOLD", "SILVER", "PLATINUM", "PALLADIUM", name="metal", create_type=False
    ),
    "postgresql",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metalprice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal', metal_enum, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('spot_price_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metal', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metalprice')
    # ### end Alembic commands ###
