"""create purchase table

Revision ID: adcf3bc00f9a
Revises: 
Create Date: 2026-10-01 13:54:44.539744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adcf3bc00f9a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metal', sa.Enum('GOLD', 'SILVER', 'PLATINUM', 'PALLADIUM', name='metal'), nullable=False),
    sa.Column('weight_oz', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('original_weight', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('original_unit', sa.Enum('GRAM', 'TROY_OUNCE', 'KILOGRAM', name='weightunit'), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('price_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('CAD', 'USD', name='currency'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase')
    # ### end Alembic commands ###
